// Checks the per-tool pages generated by scripts/build-pages.js: every page loads and opens its tool, legacy
// "#id" links still land on the right tool at its real URL, and moving between tools inside the app doesn't
// reload the page.
const { chromium } = require("playwright");
const fs = require("fs");
const path = require("path");

const BASE = process.env.TEST_BASE || "http://127.0.0.1:8899/";
const ROOT_DIR = path.join(__dirname, "..");
const MARKER = "Generated by scripts/build-pages.js";
const results = [];
const ok = (name, pass, detail = "") => { results.push({ name, pass }); console.log(`${pass ? "PASS" : "FAIL"}  ${name}${detail ? "  — " + detail : ""}`); };

(async () => {
  const slugs = fs.readdirSync(ROOT_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && fs.existsSync(path.join(ROOT_DIR, d.name, "index.html")))
    .filter((d) => fs.readFileSync(path.join(ROOT_DIR, d.name, "index.html"), "utf8").includes(MARKER))
    .map((d) => d.name).sort();
  ok("generated pages exist", slugs.length >= 40, `${slugs.length} pages`);

  const browser = await chromium.launch();
  const page = await browser.newPage();
  const pageErrors = [];
  page.on("pageerror", (e) => pageErrors.push(e.message));

  // The registry, read once, to know which tool each slug should open.
  await page.goto(BASE, { waitUntil: "load" });
  const tools = await page.evaluate(() => TOOLS.filter((t) => !t.na).map((t) => ({ id: t.id, name: t.name, slug: slugOf(t) })));
  const bySlug = Object.fromEntries(tools.map((t) => [t.slug, t]));
  ok("every generated page matches a registered tool", slugs.every((s) => bySlug[s]), slugs.filter((s) => !bySlug[s]).join(", ") || "all matched");
  ok("every available tool has a page", tools.every((t) => slugs.includes(t.slug)), tools.filter((t) => !slugs.includes(t.slug)).map((t) => t.slug).join(", ") || "all present");

  // 1) Direct load of each page opens its tool, with the right title and canonical.
  let bad = [];
  for (const slug of slugs) {
    const t = bySlug[slug]; if (!t) continue;
    await page.goto(BASE + slug + "/", { waitUntil: "domcontentloaded" });
    try {
      await page.waitForSelector(`#tool-${t.id}[data-active]`, { timeout: 10000 });
      const title = await page.title();
      const canonical = await page.$eval("link[rel=canonical]", (l) => l.getAttribute("href"));
      const cssLoaded = await page.evaluate(() => getComputedStyle(document.querySelector(".bar")).position === "sticky");
      if (!title.includes(t.name)) bad.push(`${slug}: title "${title}"`);
      if (!canonical.endsWith("/" + slug + "/")) bad.push(`${slug}: canonical ${canonical}`);
      if (!cssLoaded) bad.push(`${slug}: stylesheet not applied (bad relative path?)`);
    } catch (e) { bad.push(`${slug}: ${e.message.split("\n")[0]}`); }
  }
  ok("each page loads directly and opens its tool", bad.length === 0, bad.slice(0, 5).join(" | ") || `${slugs.length} ok`);

  // 2) Legacy hash links land on the tool at its real URL.
  await page.goto(BASE + "#pdf-to-word", { waitUntil: "domcontentloaded" });
  await page.waitForSelector("#tool-pdf-to-word[data-active]", { timeout: 10000 });
  ok("old #pdf-to-word link opens the tool and rewrites the URL", (await page.evaluate(() => location.pathname)).endsWith("/pdf-to-word/") && !(await page.evaluate(() => location.hash)));
  await page.goto(BASE + "#protect", { waitUntil: "domcontentloaded" });
  await page.waitForTimeout(300);
  ok("old link to an unavailable tool goes home", await page.$eval("#home", (h) => h.hasAttribute("data-active")) && (await page.evaluate(() => location.pathname + location.hash)).replace(/^.*\/$/, "root") === "root");

  // 3) In-app navigation: no reload, URL updates, back button works.
  await page.goto(BASE, { waitUntil: "load" });
  await page.evaluate(() => { window.__loadedAt = performance.timeOrigin; });
  await page.click(".nav a[href$='merge-pdf/']");
  await page.waitForSelector("#tool-merge[data-active]", { timeout: 5000 });
  const sameDocument = await page.evaluate(() => window.__loadedAt === performance.timeOrigin);
  ok("clicking a nav link switches tools without reloading", sameDocument && (await page.evaluate(() => location.pathname)).endsWith("/merge-pdf/"));
  await page.click(".mega-in a[href$='rotate-pdf/']", { force: true }).catch(async () => { await page.click("#menu-btn"); await page.click(".mega-in a[href$='rotate-pdf/']"); });
  await page.waitForSelector("#tool-rotate[data-active]", { timeout: 5000 });
  await page.goBack();
  await page.waitForSelector("#tool-merge[data-active]", { timeout: 5000 });
  ok("browser back returns to the previous tool", (await page.evaluate(() => location.pathname)).endsWith("/merge-pdf/"));
  await page.goBack();
  await page.waitForFunction(() => document.querySelector("#home").hasAttribute("data-active"), null, { timeout: 5000 });
  ok("back again returns home", await page.evaluate(() => location.pathname.endsWith("/") && !/[a-z]-[a-z]+\/$/.test(location.pathname.split("/").slice(-2, -1)[0] || "")));

  // 4) Share URL and nav highlight use the real URL.
  await page.goto(BASE + "compress-pdf/", { waitUntil: "domcontentloaded" });
  await page.waitForSelector("#tool-compress[data-active]");
  ok("nav highlights the current section on a direct page load", (await page.$$eval(".nav a[data-active]", (a) => a.map((x) => x.textContent))).join() === "Compress");

  ok("no uncaught page errors", pageErrors.length === 0, pageErrors.slice(0, 3).join(" | "));
  await browser.close();
  const failed = results.filter((r) => !r.pass).length;
  console.log(`\n${results.length - failed}/${results.length} passed`);
  process.exit(failed ? 1 : 0);
})().catch((e) => { console.error("HARNESS ERROR", e); process.exit(2); });
