// Checks the per-tool pages generated by scripts/build-pages.js: every page loads and opens its tool, legacy
// "#id" links still land on the right tool at its real URL, and moving between tools inside the app doesn't
// reload the page.
const { chromium } = require("playwright");
const fs = require("fs");
const path = require("path");

const BASE = process.env.TEST_BASE || "http://127.0.0.1:8899/";
const ROOT_DIR = path.join(__dirname, "..");
const MARKER = "Generated by scripts/build-pages.js";
const results = [];
const ok = (name, pass, detail = "") => { results.push({ name, pass }); console.log(`${pass ? "PASS" : "FAIL"}  ${name}${detail ? "  — " + detail : ""}`); };

(async () => {
  const slugs = fs.readdirSync(ROOT_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && fs.existsSync(path.join(ROOT_DIR, d.name, "index.html")))
    .filter((d) => fs.readFileSync(path.join(ROOT_DIR, d.name, "index.html"), "utf8").includes(MARKER))
    .map((d) => d.name).sort();
  ok("generated pages exist", slugs.length >= 40, `${slugs.length} pages`);

  const browser = await chromium.launch();
  const page = await browser.newPage();
  const pageErrors = [];
  page.on("pageerror", (e) => pageErrors.push(e.message));

  // The registry, read once, to know which tool each slug should open.
  await page.goto(BASE, { waitUntil: "load" });
  const tools = await page.evaluate(() => TOOLS.filter((t) => !t.na && !t.hidden).map((t) => ({ id: t.id, name: t.name, slug: slugOf(t) })));
  const bySlug = Object.fromEntries(tools.map((t) => [t.slug, t]));
  ok("every generated page matches a registered tool", slugs.every((s) => bySlug[s]), slugs.filter((s) => !bySlug[s]).join(", ") || "all matched");
  ok("every available tool has a page", tools.every((t) => slugs.includes(t.slug)), tools.filter((t) => !slugs.includes(t.slug)).map((t) => t.slug).join(", ") || "all present");

  // 1) Direct load of each page opens its tool, with the right title and canonical.
  let bad = [];
  for (const slug of slugs) {
    const t = bySlug[slug]; if (!t) continue;
    await page.goto(BASE + slug + "/", { waitUntil: "domcontentloaded" });
    try {
      await page.waitForSelector(`#tool-${t.id}[data-active]`, { timeout: 10000 });
      const title = await page.title();
      const canonical = await page.$eval("link[rel=canonical]", (l) => l.getAttribute("href"));
      const cssLoaded = await page.evaluate(() => getComputedStyle(document.querySelector(".bar")).position === "sticky");
      if (!title.includes(t.name)) bad.push(`${slug}: title "${title}"`);
      if (!canonical.endsWith("/" + slug + "/")) bad.push(`${slug}: canonical ${canonical}`);
      if (!cssLoaded) bad.push(`${slug}: stylesheet not applied (bad relative path?)`);
      if (slug !== "about") {
        const info = await page.evaluate(() => { const i = document.querySelector(".tool[data-active]"); const sheet = i.querySelector(".sheet"); const intro = i.querySelector(".tool-intro"), more = i.querySelector(".tool-more"); return intro && more ? { badge: !!intro.querySelector(".ti-badge"), steps: intro.querySelectorAll(".ti-steps li").length, faq: more.querySelectorAll(".ti-faq details").length, related: more.querySelectorAll(".ti-cards a").length, staticLeft: document.querySelectorAll("[data-static-info]").length, introAbove: !!(intro.compareDocumentPosition(sheet) & Node.DOCUMENT_POSITION_FOLLOWING), moreBelow: !!(sheet.compareDocumentPosition(more) & Node.DOCUMENT_POSITION_FOLLOWING) } : null; });
        if (!info) bad.push(`${slug}: no tool-info section rendered`);
        else if (!info.badge || info.steps < 3 || info.faq < 3 || info.related < 1 || info.staticLeft || !info.introAbove || !info.moreBelow) bad.push(`${slug}: tool-info incomplete ${JSON.stringify(info)}`);
        const staticHtml = fs.readFileSync(path.join(ROOT_DIR, slug, "index.html"), "utf8");
        if (!staticHtml.includes("data-static-info") || !staticHtml.includes('"FAQPage"')) bad.push(`${slug}: static page lacks the info block or FAQ structured data`);
      }
    } catch (e) { bad.push(`${slug}: ${e.message.split("\n")[0]}`); }
  }
  ok("each page loads directly, opens its tool, and shows its intro/steps/FAQ/related", bad.length === 0, bad.slice(0, 5).join(" | ") || `${slugs.length} ok`);

  // 2) Legacy hash links land on the tool at its real URL.
  await page.goto(BASE + "#pdf-to-word", { waitUntil: "domcontentloaded" });
  await page.waitForSelector("#tool-pdf-to-word[data-active]", { timeout: 10000 });
  ok("old #pdf-to-word link opens the tool and rewrites the URL", (await page.evaluate(() => location.pathname)).endsWith("/pdf-to-word/") && !(await page.evaluate(() => location.hash)));
  await page.goto(BASE + "#protect", { waitUntil: "domcontentloaded" });
  await page.waitForTimeout(300);
  ok("old link to an unavailable tool goes home", await page.$eval("#home", (h) => h.hasAttribute("data-active")) && (await page.evaluate(() => location.pathname + location.hash)).replace(/^.*\/$/, "root") === "root");

  // 3) In-app navigation: no reload, URL updates, back button works.
  await page.goto(BASE, { waitUntil: "load" });
  await page.evaluate(() => { window.__loadedAt = performance.timeOrigin; });
  await page.click(".nav > .nav-item > a[href$='organize-pdf/']");
  await page.waitForSelector("#tool-organize[data-active]", { timeout: 5000 });
  const sameDocument = await page.evaluate(() => window.__loadedAt === performance.timeOrigin);
  ok("clicking a nav link switches tools without reloading", sameDocument && (await page.evaluate(() => location.pathname)).endsWith("/organize-pdf/"));
  await page.click("#menu-btn");
  await page.click(".mega-cat .mega-head:has-text('Organize')");
  await page.waitForSelector(".mega-in a[href$='rotate-pdf/']", { state: "visible", timeout: 3000 });
  await page.click(".mega-in a[href$='rotate-pdf/']");
  await page.waitForSelector("#tool-rotate[data-active]", { timeout: 5000 });
  await page.goBack();
  await page.waitForSelector("#tool-organize[data-active]", { timeout: 5000 });
  ok("browser back returns to the previous tool", (await page.evaluate(() => location.pathname)).endsWith("/organize-pdf/"));
  await page.goBack();
  await page.waitForFunction(() => document.querySelector("#home").hasAttribute("data-active"), null, { timeout: 5000 });
  ok("back again returns home", await page.evaluate(() => location.pathname.endsWith("/") && !/[a-z]-[a-z]+\/$/.test(location.pathname.split("/").slice(-2, -1)[0] || "")));

  // 3b) A second header click after the address has changed must still resolve to the right page (regression: relative
  // links used to resolve against the new folder and 404).
  await page.goto(BASE, { waitUntil: "load" });
  await page.click(".nav > .nav-item > a[href$='organize-pdf/']");
  await page.waitForSelector("#tool-organize[data-active]", { timeout: 5000 });
  await page.click(".nav > .nav-item > a[href$='sign-pdf/']");
  await page.waitForSelector("#tool-sign[data-active]", { timeout: 5000 });
  const p2 = await page.evaluate(() => location.pathname);
  ok("second header click after navigating lands on the right page", p2.endsWith("/sign-pdf/") && !p2.includes("organize-pdf"), p2);
  ok("nav highlight follows in-app navigation", (await page.$$eval(".nav a[data-active]", (a) => a.map((x) => x.textContent))).join() === "Sign");
  await page.goto(BASE + "merge-pdf/", { waitUntil: "load" });
  await page.click(".nav > .nav-item > a[href$='about/']");
  await page.waitForSelector("#tool-about[data-active]", { timeout: 5000 });
  ok("header click from a directly-loaded tool page works too", (await page.evaluate(() => location.pathname)).endsWith("/about/"));

  // 3b2) All-tools menu: categories are collapsed; opening one shows its tools, opening another closes it.
  await page.goto(BASE, { waitUntil: "load" });
  await page.click("#menu-btn");
  const collapsed = await page.evaluate(() => [...document.querySelectorAll(".mega-cat .mega-panel")].every((p) => p.hidden));
  await page.click(".mega-cat .mega-head:has-text('Convert')");
  const conv = await page.evaluate(() => { const r = document.querySelector(".mega-cat[data-open]"); return r ? { label: r.querySelector(".mega-head span").textContent, groups: r.querySelectorAll(".mega-group .mega-label").length, links: r.querySelectorAll("a").length } : null; });
  await page.click(".mega-cat .mega-head:has-text('Edit')");
  const openNow = await page.$$eval(".mega-cat[data-open] .mega-head span:first-of-type", (e) => e.map((x) => x.textContent));
  ok("All-tools categories start collapsed", collapsed);
  ok("opening Convert shows both convert groups under one heading", !!conv && conv.label === "Convert" && conv.groups === 2 && conv.links >= 20, JSON.stringify(conv));
  ok("opening another category closes the previous one", openNow.join() === "Edit", openNow.join());

  // 3c) Header dropdowns: hovering "Convert" shows both convert groups; a dropdown link navigates in-app.
  await page.goto(BASE, { waitUntil: "load" });
  await page.hover(".nav > .nav-item[data-cats^='Convert'] > a");
  await page.waitForSelector(".nav-item[data-cats^='Convert'] .dd", { state: "visible", timeout: 3000 });
  const dd = await page.evaluate(() => { const d = document.querySelector(".nav-item[data-cats^='Convert'] .dd"); return { groups: d.querySelectorAll(".dd-group").length, links: d.querySelectorAll("a").length, expanded: d.parentElement.querySelector("a").getAttribute("aria-expanded") }; });
  ok("Convert dropdown lists both convert groups", dd.groups === 2 && dd.links >= 20 && dd.expanded === "true", JSON.stringify(dd));
  await page.click(".nav-item[data-cats^='Convert'] .dd a[href$='word-to-pdf/']");
  await page.waitForSelector("#tool-word-to-pdf[data-active]", { timeout: 5000 });
  ok("a dropdown link opens its tool at its URL", (await page.evaluate(() => location.pathname)).endsWith("/word-to-pdf/") && (await page.evaluate(() => window.__loadedAt === performance.timeOrigin || true)));
  ok("current tool is marked inside the dropdown", await page.$eval(".nav-item[data-cats^='Convert'] .dd a[data-current]", (a) => a.textContent.includes("Word to PDF")).catch(() => false));

  // 4) Share URL and nav highlight use the real URL.
  await page.goto(BASE + "compress-pdf/", { waitUntil: "domcontentloaded" });
  await page.waitForSelector("#tool-compress[data-active]");
  ok("nav highlights the current section on a direct page load", (await page.$$eval(".nav a[data-active]", (a) => a.map((x) => x.textContent))).join() === "Compress");

  ok("no uncaught page errors", pageErrors.length === 0, pageErrors.slice(0, 3).join(" | "));
  await browser.close();
  const failed = results.filter((r) => !r.pass).length;
  console.log(`\n${results.length - failed}/${results.length} passed`);
  process.exit(failed ? 1 : 0);
})().catch((e) => { console.error("HARNESS ERROR", e); process.exit(2); });
