#!/usr/bin/env node
// Generates one static page per tool (compress-pdf/index.html, pdf-to-word/index.html, …) plus sitemap.xml.
//
// Why: the app is a single page that switches tools client-side, but search engines treat "one page" literally —
// they ignore everything after a "#". Giving every tool its own URL, with its own title, description and
// structured data, lets each one be indexed and linked on its own. The generated pages are thin: the same
// markup as index.html with tool-specific <head> tags and paths adjusted for living one folder down. app.js
// recognises the URL and opens the right tool, and in-app navigation keeps using pushState, so nothing about
// how the site works at runtime changes.
//
// Run it after adding, renaming or removing a tool, then commit the output:
//     node scripts/build-pages.js
// It reads the tool list from the app itself (in a headless browser via Playwright, which lives in tests/),
// so the pages can never drift from what app.js actually registers.
//
// Options:  --base <url>   use an already-running server for the site instead of starting one
//           --dry          report what would change without writing anything

const fs = require("fs");
const path = require("path");
const http = require("http");
const vm = require("vm");

const ROOT_DIR = path.join(__dirname, "..");
const args = process.argv.slice(2);
const opt = (name) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : null; };
const DRY = args.includes("--dry");
const MARKER = "<!-- Generated by scripts/build-pages.js from index.html. Edit index.html and re-run; do not edit this file. -->";

function loadPlaywright() {
  for (const p of [path.join(ROOT_DIR, "tests", "node_modules", "playwright"), "playwright"]) {
    try { return require(p); } catch {}
  }
  console.error("Playwright not found. Run `npm install` inside tests/ first.");
  process.exit(1);
}

// Minimal static server for ROOT_DIR, only used when --base isn't given.
function serve() {
  const types = { ".html": "text/html", ".js": "text/javascript", ".css": "text/css", ".json": "application/json",
    ".svg": "image/svg+xml", ".png": "image/png", ".xml": "application/xml", ".txt": "text/plain", ".ttf": "font/ttf", ".wasm": "application/wasm" };
  const srv = http.createServer((req, res) => {
    let p = decodeURIComponent(req.url.split("?")[0]);
    if (p.endsWith("/")) p += "index.html";
    const file = path.join(ROOT_DIR, p);
    if (!file.startsWith(ROOT_DIR) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) { res.writeHead(404); return res.end(); }
    res.writeHead(200, { "Content-Type": types[path.extname(file)] || "application/octet-stream" });
    fs.createReadStream(file).pipe(res);
  });
  return new Promise((resolve) => srv.listen(0, "127.0.0.1", () => resolve({ srv, base: `http://127.0.0.1:${srv.address().port}/` })));
}

async function readRegistry(base) {
  const { chromium } = loadPlaywright();
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage();
    const errors = [];
    page.on("pageerror", (e) => errors.push(e.message));
    await page.goto(base, { waitUntil: "load" });
    await page.waitForFunction(() => typeof TOOLS !== "undefined" && TOOLS.length > 0, null, { timeout: 15000 });
    const tools = await page.evaluate(() => TOOLS.map((t) => ({ id: t.id, cat: t.cat, name: t.name, desc: t.desc || "", na: t.na || "", hidden: !!t.hidden, slug: slugOf(t) })));
    if (errors.length) console.warn("Page errors while reading the registry:\n  " + errors.join("\n  "));
    return tools;
  } finally { await browser.close(); }
}

const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

// assets/tool-content.js is a browser script; evaluate it against a bare `window` to get the content and renderer.
function loadToolContent() {
  const win = {};
  vm.runInNewContext(fs.readFileSync(path.join(ROOT_DIR, "assets", "tool-content.js"), "utf8"), { window: win });
  return { content: win.TOOL_CONTENT || {}, render: win.renderToolInfo };
}

function toolPage(indexHtml, t, site, allSlugs, tools, tc) {
  let h = indexHtml;
  const url = site + t.slug + "/";
  const title = `${t.name} — free, private, in your browser | Loomsheet`;
  const desc = `${t.desc} Free, private, runs in your browser — nothing is uploaded.`;

  h = h.replace(/<title>[^<]*<\/title>/, `<title>${esc(title)}</title>`);
  h = h.replace(/<meta name="description" content="[^"]*">/, `<meta name="description" content="${esc(desc)}">`);
  h = h.replace(/<link rel="canonical" href="[^"]*">/, `<link rel="canonical" href="${url}">`);
  h = h.replace(/<meta property="og:url" content="[^"]*">/, `<meta property="og:url" content="${url}">`);
  h = h.replace(/<meta property="og:title" content="[^"]*">/, `<meta property="og:title" content="${esc(t.name + " — Loomsheet")}">`);
  h = h.replace(/<meta property="og:description" content="[^"]*">/, `<meta property="og:description" content="${esc(desc)}">`);
  h = h.replace(/<meta name="twitter:title" content="[^"]*">/, `<meta name="twitter:title" content="${esc(t.name + " — Loomsheet")}">`);
  h = h.replace(/<meta name="twitter:description" content="[^"]*">/, `<meta name="twitter:description" content="${esc(desc)}">`);
  h = h.replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/, `<script type="application/ld+json">${JSON.stringify({
    "@context": "https://schema.org", "@type": "WebApplication", name: t.name, url,
    applicationCategory: "UtilitiesApplication", operatingSystem: "Any", browserRequirements: "Requires JavaScript",
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, description: desc,
    isPartOf: { "@type": "WebSite", name: "Loomsheet", url: site },
  })}</script>`);

  // Real content for this tool, straight from assets/tool-content.js, so crawlers see text rather than an empty shell.
  // The app removes this block and renders its own (identical) copy under the tool.
  const c = tc.content[t.id];
  if (c && tc.render) {
    const info = tc.render(t, tools, { link: (r) => "../" + r.slug + "/" });
    h = h.replace(/<footer>/, `<div data-static-info>${info}</div>\n  <footer>`);
    const faq = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: c.faq.map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) };
    h = h.replace(/(<script type="application\/ld\+json">[\s\S]*?<\/script>)/, `$1\n<script type="application/ld+json">${JSON.stringify(faq)}</script>`);
  }

  // Living one folder down: point shared assets and site links back up to the root.
  h = h.replace(/(href|src)="assets\//g, '$1="../assets/');
  h = h.replace(/href="manifest\.json"/g, 'href="../manifest.json"');
  h = h.replace(/href="\.\/"/g, 'href="../"');
  for (const slug of allSlugs) h = h.replace(new RegExp(`href="${slug}/"`, "g"), `href="../${slug}/"`);

  h = h.replace(/^(<!DOCTYPE html>\s*)/i, `$1${MARKER}\n`);
  return h;
}

(async () => {
  let base = opt("--base"), server = null;
  if (!base) { server = await serve(); base = server.base; }
  let tools;
  try { tools = await readRegistry(base); } finally { if (server) server.srv.close(); }

  const live = tools.filter((t) => !t.na && !t.hidden);
  const tc = loadToolContent();
  const missing = live.filter((t) => t.id !== "about" && !tc.content[t.id]).map((t) => t.id);
  if (missing.length) console.warn("No entry in assets/tool-content.js for: " + missing.join(", "));
  const slugs = live.map((t) => t.slug);
  const dupes = slugs.filter((s, i) => slugs.indexOf(s) !== i);
  if (dupes.length) { console.error("Two tools share a URL slug — rename one: " + [...new Set(dupes)].join(", ")); process.exit(1); }

  const indexPath = path.join(ROOT_DIR, "index.html");
  let index = fs.readFileSync(indexPath, "utf8");
  const site = (index.match(/<link rel="canonical" href="([^"]+)">/) || [])[1];
  if (!site || !site.endsWith("/")) { console.error("index.html needs a <link rel=\"canonical\"> ending in / — it's used as the site's absolute URL."); process.exit(1); }

  // 1) Normalise index.html's own links: "#id" -> "slug/", "#" -> "./".
  const before = index;
  for (const t of live) index = index.replace(new RegExp(`href="#${t.id}"`, "g"), `href="${t.slug}/"`);
  index = index.replace(/href="#"(?![^>]*id="foot-personalize")/g, 'href="./"');
  const leftover = [...index.matchAll(/href="#([a-z0-9-]+)"/g)].map((m) => m[1]).filter((id) => id !== "main" && !live.some((t) => t.id === id));
  if (leftover.length) console.warn("index.html links to tools that don't exist or aren't available: " + leftover.join(", "));
  if (index !== before && !DRY) fs.writeFileSync(indexPath, index);

  // 2) One page per tool.
  let written = 0, unchanged = 0;
  for (const t of live) {
    const dir = path.join(ROOT_DIR, t.slug);
    const file = path.join(dir, "index.html");
    const html = toolPage(index, t, site, slugs, live, tc);
    if (fs.existsSync(file) && fs.readFileSync(file, "utf8") === html) { unchanged++; continue; }
    if (!DRY) { fs.mkdirSync(dir, { recursive: true }); fs.writeFileSync(file, html); }
    written++;
  }

  // 3) Remove pages for tools that no longer exist (only ones we generated — they carry the marker).
  let removed = 0;
  for (const entry of fs.readdirSync(ROOT_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory() || slugs.includes(entry.name)) continue;
    const f = path.join(ROOT_DIR, entry.name, "index.html");
    if (fs.existsSync(f) && fs.readFileSync(f, "utf8").includes(MARKER)) { if (!DRY) fs.rmSync(path.join(ROOT_DIR, entry.name), { recursive: true }); removed++; }
  }

  // 4) sitemap.xml with real URLs. (No <lastmod>: it would change on every run and make the CI freshness check fail.)
  const urls = [{ loc: site, pri: "1.0" }, ...live.map((t) => ({ loc: site + t.slug + "/", pri: t.id === "about" ? "0.5" : "0.8" }))];
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    urls.map((u) => `  <url><loc>${u.loc}</loc><priority>${u.pri}</priority></url>`).join("\n") + `\n</urlset>\n`;
  const sitemapPath = path.join(ROOT_DIR, "sitemap.xml");
  const sitemapChanged = !fs.existsSync(sitemapPath) || fs.readFileSync(sitemapPath, "utf8") !== sitemap;
  if (sitemapChanged && !DRY) fs.writeFileSync(sitemapPath, sitemap);

  console.log(`${DRY ? "[dry run] " : ""}${live.length} tool pages: ${written} written, ${unchanged} unchanged, ${removed} stale removed; sitemap ${sitemapChanged ? "updated" : "unchanged"}; index.html links ${index !== before ? "normalised" : "already clean"}.`);
  console.log(live.map((t) => `  ${t.slug}/  ←  ${t.name}`).join("\n"));
})().catch((e) => { console.error(e); process.exit(1); });
